# /lib/Makefile
# $Id$
#
# This file is a part of PhobOS operating system.
# Copyright (c) 2011, Artyom Lebedev <artyom.lebedev@gmail.com>
# All rights reserved.
# See COPYING file for copyright details.

SUBDIRS = startup sl_startup user common elf module_testing module_testing2

include $(PHOBOS_ROOT)/make/make.mak
