# /lib/Makefile
# $Id$
#
# This file is a part of PhobOS operating system.
# Copyright (c)AST 2009. Written by Artemy Lebedev.

SUBDIRS = startup user common elf module_testing

include $(PHOBOS_ROOT)/make/make.mak
