# /phobos/lib/module_testing_2/Makefile
# $Id$
#
# This file is a part of PhobOS operating system.
# Copyright (c) 2011, Artyom Lebedev <artyom.lebedev@gmail.com>
# All rights reserved.
# See COPYING file for copyright details.

LIB = module_testing2

INCLUDES += $(PHOBOS_ROOT)/bin/module_testing

EXPORTABLE = 1

include $(PHOBOS_ROOT)/make/make.mak
