# /lib/startup/Makefile
# $Id$
#
# This file is a part of PhobOS operating system.
# Copyright ©AST 2009. Written by Artemy Lebedev.

OBJ = $(APP_RUNTIME_LIB_NAME)

include $(PHOBOS_ROOT)/make/make.mak
