# /lib/startup/Makefile
# $Id$
#
# This file is a part of PhobOS operating system.
# Copyright (c)AST 2009. Written by Artemy Lebedev.

LIB = $(APP_RUNTIME_LIB_NAME)

STATIC = 1

include $(PHOBOS_ROOT)/make/make.mak
