# /kernel/unit_test/Makefile
# $Id$
#
# This file is a part of PhobOS operating system.
# Copyright (c) 2011, Artyom Lebedev <artyom.lebedev@gmail.com>
# All rights reserved.
# See COPYING file for copyright details.

UNIT_SRCS = kern/lock.cpp

include $(KERNROOT)/make/unit_test.mak
