# /kernel/lib/Tree/Makefile
# $Id$
#
# This file is a part of PhobOS operating system.
# Copyright (c) 2011, Artyom Lebedev <artyom.lebedev@gmail.com>
# All rights reserved.
# See COPYING file for copyright details.

ifdef KERNROOT

include ${KERNROOT}/make/make.mak

else

LIB = $(COMMON_LIB_NAME)

include $(PHOBOS_ROOT)/make/make.mak

endif
