# /phobos/lib/shlib_startup/Makefile
# $Id$
#
# This file is a part of PhobOS operating system.
# Copyright (c)AST 2009. Written by Artemy Lebedev.

OBJ = $(SL_RUNTIME_LIB_NAME)

include $(PHOBOS_ROOT)/make/make.mak
