# /lib/startup/Makefile
# $Id$
#
# This file is a part of PhobOS operating system.
# Copyright (c) 2011, Artyom Lebedev <artyom.lebedev@gmail.com>
# All rights reserved.
# See COPYING file for copyright details.

LIB = $(APP_RUNTIME_LIB_NAME)

STATIC = 1

include $(PHOBOS_ROOT)/make/make.mak
