# /phobos/lib/module_testing/Makefile
# $Id$
#
# This file is a part of PhobOS operating system.
# Copyright (c)AST 2009. Written by Artemy Lebedev.

LIB = module_testing

LIBS += elf common

INCLUDES += $(PHOBOS_ROOT)/bin/module_testing

include $(PHOBOS_ROOT)/make/make.mak