# /kernel/lib/Makefile
# $Id$
#
# This file is a part of PhobOS operating system.
# Copyright (c) 2011, Artyom Lebedev <artyom.lebedev@gmail.com>
# All rights reserved.
# See COPYING file for copyright details.

SUBDIRS = $(COMMON_LIB_DIR)

include ${KERNROOT}/make/make.mak
