# /kernel/Makefile
# $Id$
#
# This file is a part of PhobOS operating system.
# Copyright (c) 2011, Artyom Lebedev <artyom.lebedev@gmail.com>
# All rights reserved.
# See COPYING file for copyright details.

export KERNROOT = $(PHOBOS_ROOT)/kernel
MAKEIMAGE = 1

SUBDIRS = init lib dev mem unit_test kern kdb vfs fs gate

include $(KERNROOT)/make/make.mak
