# /kernel/unit_test/Makefile
# $Id$
#
# This file is a part of PhobOS operating system.
# Copyright ©AST 2009. Written by Artemy Lebedev.

UNIT_SRCS= lib/Tree32.cpp

include $(KERNROOT)/make/unit_test.mak
